// Angebot- und Nachfrage-Diagramm Template
// Achsen, Beschriftungen, zwei Kurven – Schüler zeichnen darauf

export const angebotNachfrageTemplate = {
  type: "excalidraw",
  version: 2,
  source: "econ-draw",
  elements: [
    // Y-Achse (Preis)
    {
      id: "y-axis",
      type: "arrow",
      x: 120,
      y: 500,
      width: 0,
      height: -380,
      angle: 0,
      strokeColor: "#1a1a1a",
      backgroundColor: "transparent",
      fillStyle: "solid",
      strokeWidth: 2,
      strokeStyle: "solid",
      roughness: 0,
      opacity: 100,
      points: [[0, 0], [0, -380]],
      lastCommittedPoint: null,
      startBinding: null,
      endBinding: null,
      startArrowhead: null,
      endArrowhead: "arrow",
      roundness: null,
      frameId: null,
      index: "a0",
      version: 1,
      versionNonce: 1,
      isDeleted: false,
      groupIds: [],
      boundElements: [],
      updated: 1,
      link: null,
      locked: true,
    },
    // X-Achse (Menge)
    {
      id: "x-axis",
      type: "arrow",
      x: 120,
      y: 500,
      width: 450,
      height: 0,
      angle: 0,
      strokeColor: "#1a1a1a",
      backgroundColor: "transparent",
      fillStyle: "solid",
      strokeWidth: 2,
      strokeStyle: "solid",
      roughness: 0,
      opacity: 100,
      points: [[0, 0], [450, 0]],
      lastCommittedPoint: null,
      startBinding: null,
      endBinding: null,
      startArrowhead: null,
      endArrowhead: "arrow",
      roundness: null,
      frameId: null,
      index: "a1",
      version: 1,
      versionNonce: 2,
      isDeleted: false,
      groupIds: [],
      boundElements: [],
      updated: 1,
      link: null,
      locked: true,
    },
    // Label Y-Achse: Preis (P)
    {
      id: "label-y",
      type: "text",
      x: 60,
      y: 105,
      width: 50,
      height: 28,
      angle: 0,
      strokeColor: "#1a1a1a",
      backgroundColor: "transparent",
      fillStyle: "solid",
      strokeWidth: 1,
      strokeStyle: "solid",
      roughness: 0,
      opacity: 100,
      text: "Preis (P)",
      fontSize: 18,
      fontFamily: 1,
      textAlign: "center",
      verticalAlign: "top",
      baseline: 16,
      containerId: null,
      originalText: "Preis (P)",
      roundness: null,
      frameId: null,
      index: "a2",
      version: 1,
      versionNonce: 3,
      isDeleted: false,
      groupIds: [],
      boundElements: [],
      updated: 1,
      link: null,
      locked: true,
    },
    // Label X-Achse: Menge (Q)
    {
      id: "label-x",
      type: "text",
      x: 530,
      y: 490,
      width: 70,
      height: 28,
      angle: 0,
      strokeColor: "#1a1a1a",
      backgroundColor: "transparent",
      fillStyle: "solid",
      strokeWidth: 1,
      strokeStyle: "solid",
      roughness: 0,
      opacity: 100,
      text: "Menge (Q)",
      fontSize: 18,
      fontFamily: 1,
      textAlign: "left",
      verticalAlign: "top",
      baseline: 16,
      containerId: null,
      originalText: "Menge (Q)",
      roundness: null,
      frameId: null,
      index: "a3",
      version: 1,
      versionNonce: 4,
      isDeleted: false,
      groupIds: [],
      boundElements: [],
      updated: 1,
      link: null,
      locked: true,
    },
    // Nachfragekurve (D) – fallend, blau
    {
      id: "nachfrage",
      type: "line",
      x: 150,
      y: 160,
      width: 360,
      height: 300,
      angle: 0,
      strokeColor: "#1971c2",
      backgroundColor: "transparent",
      fillStyle: "solid",
      strokeWidth: 2.5,
      strokeStyle: "solid",
      roughness: 1,
      opacity: 100,
      points: [[0, 0], [360, 300]],
      lastCommittedPoint: null,
      roundness: { type: 2 },
      frameId: null,
      index: "a4",
      version: 1,
      versionNonce: 5,
      isDeleted: false,
      groupIds: [],
      boundElements: [],
      updated: 1,
      link: null,
      locked: true,
    },
    // Label Nachfrage: N
    {
      id: "label-nachfrage",
      type: "text",
      x: 500,
      y: 440,
      width: 20,
      height: 28,
      angle: 0,
      strokeColor: "#1971c2",
      backgroundColor: "transparent",
      fillStyle: "solid",
      strokeWidth: 1,
      strokeStyle: "solid",
      roughness: 0,
      opacity: 100,
      text: "N",
      fontSize: 22,
      fontFamily: 1,
      textAlign: "center",
      verticalAlign: "top",
      baseline: 18,
      containerId: null,
      originalText: "N",
      roundness: null,
      frameId: null,
      index: "a5",
      version: 1,
      versionNonce: 6,
      isDeleted: false,
      groupIds: [],
      boundElements: [],
      updated: 1,
      link: null,
      locked: true,
    },
    // Angebotskurve (A) – steigend, rot
    {
      id: "angebot",
      type: "line",
      x: 150,
      y: 460,
      width: 360,
      height: -300,
      angle: 0,
      strokeColor: "#c2255c",
      backgroundColor: "transparent",
      fillStyle: "solid",
      strokeWidth: 2.5,
      strokeStyle: "solid",
      roughness: 1,
      opacity: 100,
      points: [[0, 0], [360, -300]],
      lastCommittedPoint: null,
      roundness: { type: 2 },
      frameId: null,
      index: "a6",
      version: 1,
      versionNonce: 7,
      isDeleted: false,
      groupIds: [],
      boundElements: [],
      updated: 1,
      link: null,
      locked: true,
    },
    // Label Angebot: A
    {
      id: "label-angebot",
      type: "text",
      x: 500,
      y: 145,
      width: 20,
      height: 28,
      angle: 0,
      strokeColor: "#c2255c",
      backgroundColor: "transparent",
      fillStyle: "solid",
      strokeWidth: 1,
      strokeStyle: "solid",
      roughness: 0,
      opacity: 100,
      text: "A",
      fontSize: 22,
      fontFamily: 1,
      textAlign: "center",
      verticalAlign: "top",
      baseline: 18,
      containerId: null,
      originalText: "A",
      roundness: null,
      frameId: null,
      index: "a7",
      version: 1,
      versionNonce: 8,
      isDeleted: false,
      groupIds: [],
      boundElements: [],
      updated: 1,
      link: null,
      locked: true,
    },
    // Gleichgewichtspunkt (Kreis)
    {
      id: "gleichgewicht",
      type: "ellipse",
      x: 288,
      y: 288,
      width: 16,
      height: 16,
      angle: 0,
      strokeColor: "#2f9e44",
      backgroundColor: "#2f9e44",
      fillStyle: "solid",
      strokeWidth: 1,
      strokeStyle: "solid",
      roughness: 0,
      opacity: 100,
      roundness: { type: 3 },
      frameId: null,
      index: "a8",
      version: 1,
      versionNonce: 9,
      isDeleted: false,
      groupIds: [],
      boundElements: [],
      updated: 1,
      link: null,
      locked: true,
    },
    // Label Gleichgewicht: G*
    {
      id: "label-gleichgewicht",
      type: "text",
      x: 310,
      y: 280,
      width: 30,
      height: 24,
      angle: 0,
      strokeColor: "#2f9e44",
      backgroundColor: "transparent",
      fillStyle: "solid",
      strokeWidth: 1,
      strokeStyle: "solid",
      roughness: 0,
      opacity: 100,
      text: "G*",
      fontSize: 18,
      fontFamily: 1,
      textAlign: "left",
      verticalAlign: "top",
      baseline: 16,
      containerId: null,
      originalText: "G*",
      roundness: null,
      frameId: null,
      index: "a9",
      version: 1,
      versionNonce: 10,
      isDeleted: false,
      groupIds: [],
      boundElements: [],
      updated: 1,
      link: null,
      locked: true,
    },
    // Gestrichelte Linie: Gleichgewichtspreis horizontal
    {
      id: "line-p-star",
      type: "line",
      x: 120,
      y: 296,
      width: 176,
      height: 0,
      angle: 0,
      strokeColor: "#2f9e44",
      backgroundColor: "transparent",
      fillStyle: "solid",
      strokeWidth: 1.5,
      strokeStyle: "dashed",
      roughness: 0,
      opacity: 80,
      points: [[0, 0], [176, 0]],
      lastCommittedPoint: null,
      roundness: null,
      frameId: null,
      index: "a10",
      version: 1,
      versionNonce: 11,
      isDeleted: false,
      groupIds: [],
      boundElements: [],
      updated: 1,
      link: null,
      locked: true,
    },
    // Label P*
    {
      id: "label-p-star",
      type: "text",
      x: 88,
      y: 286,
      width: 25,
      height: 22,
      angle: 0,
      strokeColor: "#2f9e44",
      backgroundColor: "transparent",
      fillStyle: "solid",
      strokeWidth: 1,
      strokeStyle: "solid",
      roughness: 0,
      opacity: 100,
      text: "P*",
      fontSize: 16,
      fontFamily: 1,
      textAlign: "center",
      verticalAlign: "top",
      baseline: 14,
      containerId: null,
      originalText: "P*",
      roundness: null,
      frameId: null,
      index: "a11",
      version: 1,
      versionNonce: 12,
      isDeleted: false,
      groupIds: [],
      boundElements: [],
      updated: 1,
      link: null,
      locked: true,
    },
    // Gestrichelte Linie: Gleichgewichtsmenge vertikal
    {
      id: "line-q-star",
      type: "line",
      x: 296,
      y: 304,
      width: 0,
      height: 196,
      angle: 0,
      strokeColor: "#2f9e44",
      backgroundColor: "transparent",
      fillStyle: "solid",
      strokeWidth: 1.5,
      strokeStyle: "dashed",
      roughness: 0,
      opacity: 80,
      points: [[0, 0], [0, 196]],
      lastCommittedPoint: null,
      roundness: null,
      frameId: null,
      index: "a12",
      version: 1,
      versionNonce: 13,
      isDeleted: false,
      groupIds: [],
      boundElements: [],
      updated: 1,
      link: null,
      locked: true,
    },
    // Label Q*
    {
      id: "label-q-star",
      type: "text",
      x: 282,
      y: 508,
      width: 25,
      height: 22,
      angle: 0,
      strokeColor: "#2f9e44",
      backgroundColor: "transparent",
      fillStyle: "solid",
      strokeWidth: 1,
      strokeStyle: "solid",
      roughness: 0,
      opacity: 100,
      text: "Q*",
      fontSize: 16,
      fontFamily: 1,
      textAlign: "center",
      verticalAlign: "top",
      baseline: 14,
      containerId: null,
      originalText: "Q*",
      roundness: null,
      frameId: null,
      index: "a13",
      version: 1,
      versionNonce: 14,
      isDeleted: false,
      groupIds: [],
      boundElements: [],
      updated: 1,
      link: null,
      locked: true,
    },
  ],
  appState: {
    viewBackgroundColor: "#ffffff",
    gridSize: null,
  },
};
